### ISSUE TITLE
Missing file 'utils_plot'

### ISSUE THREAD

**Issue by kari15** [danpak94/Deep-Cardiac-Volumetric-Mesh#1]
I was following the steps of "Quick start example: evaluation" on README.md, and came across an issue "ModuleNotFoundError: No module named 'utils_plot'" when I ran the code "python evaluate_laa_test.py". I searched for the file "utils_plot.py" in Deep-Cardiac-Volumetric-Mesh-tmi2022 but didn't see one. Can you add the file to the package? Thank you!

**Comment by kari15** [comment]
https://github.com/danpak94/Deep-Cardiac-Volumetric-Mesh/blob/ba36adfcf9ab176e80a2406eafb1b7187ea88341/evaluate_laa_test.py#L21

**Comment by danpak94** [comment]
Hi, thanks for your interest. I added the file. It's been a while since I updated the public repo, so please let me know if you run into any further issues after the update.

**Comment by kari15** [comment]
Hi, thank you for your quick response and adding the file to the repo!
